# Generated by Django 4.1.7 on 2023-03-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=50, verbose_name='skill_name'),
        ),
        migrations.CreateModel(
            name='About_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='my_name')),
                ('description', models.TextField(verbose_name='my_description')),
                ('image', models.ImageField(upload_to='my_image', verbose_name='image')),
                ('whatsapp', models.CharField(blank=True, max_length=150, null=True, verbose_name='whatsapp_id')),
                ('telegram', models.CharField(blank=True, max_length=150, null=True, verbose_name='telegram_id')),
                ('linkdin', models.CharField(blank=True, max_length=150, null=True, verbose_name='linkdin_id')),
                ('github', models.CharField(blank=True, max_length=150, null=True, verbose_name='github_id')),
                ('instagram', models.CharField(blank=True, max_length=150, null=True, verbose_name='instagram_id')),
                ('phone', models.CharField(max_length=11, verbose_name='my_number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('skills', models.ManyToManyField(to='about_me_app.skills', verbose_name='skills')),
            ],
            options={
                'verbose_name': 'About_me',
                'verbose_name_plural': 'About_me',
            },
        ),
    ]
